import { BillOfLading } from "./types";

export const BillOfLadingSample: BillOfLading = {
  $template: {
    type: "EMBEDDED_RENDERER",
    name: "BILL_OF_LADING",
    url: "http://localhost:3000"
  },
  links: {
    self: {
      href:
        "https://action.openattestation.com?q=%7B%22type%22%3A%22DOCUMENT%22%2C%22payload%22%3A%7B%22uri%22%3A%22https%3A%2F%2Fapi-rinkeby.tradetrust.io%2Fstorage%2F522f6929-2878-41d6-bd17-adc9170d897d%22%2C%22key%22%3A%22e834419b95a798f44323d2f590097b8566532eac22977219244048f0167d243b%22%2C%22permittedActions%22%3A%5B%22STORE%22%5D%2C%22redirect%22%3A%22https%3A%2F%2Frinkeby.tradetrust.io%2F%22%7D%7D"
    }
  },
  data: {
    BLNumber: "182BA02365",
    CarrierName: "",
    TransportDocumentIssuer: "",
    Shipper: "NEW ASIA OIL, INCORPORATED",
    ShipperAddress:
      "KM. 21 BUDBUD BRGY. BUNAWAN,\nDAVAO CITY, PHILIPPINES 8000\nSHIN\nNO. 2, JIANGUO RD., NEIPU TOWNSHIP,",
    ShipperCountry: "",
    ShipperPhoneNumber: "",
    ShipperEmail: "",
    ShipperFax: "",
    Consignee: "",
    ConsigneeAddress: "PINGTUNG COUNTY 91252, TAIWAN",
    ConsigneeCountry: "",
    ConsigneePhoneNumber: "",
    ConsigneeEmail: "",
    ConsigneeFax: "",
    FreightPayer: "",
    NotifyParty: "CHUEN SHIN FEEDS CO., LTD.",
    NotifyPartyAddress: "NO. 2, JIANGUO RD., NEIPU TOWNSHIP,\nPINGTUNG COUNTY TAIWAN",
    NotifyPartyCountry: "",
    NotifyPartyPhoneNumber: "TEL:886-8-7799090",
    NotifyPartyEmail: "WHLUO331817",
    NotifyPartyFax: "",
    AlsoNotify: "",
    ShipperForwardingAgent: "",
    ConsigneeForwardingAgent: "",
    PlaceOfReceipt: "",
    PortOfLoading: "",
    PortOfDischarge: "KAOHSIUNG,",
    PlaceOfDelivery: "",
    OnwardInlandRouting: "",
    ServiceType: "",
    ShipmentTerms: '"FREIGHT PREPAID"',
    Vessel: "WAN HAI",
    VoyageNumber: "N472",
    MarksAndNumbers: "",
    DescriptionOfGoods: "PHILIPPINES",
    Commodity: "",
    HsCode: "",
    CargoGrossWeight: "WHLK992402",
    VerifiedGrossMass: "",
    TotalContainerWeight: "",
    Measurement: "",
    FreightPayableAt: "",
    PlaceOfIssue: "DAVAO",
    DateOfIssue: "SEP 18 2021",
    NumberOfOriginalBL: "ZERO",
    NumberOfBLCopies: "",
    CarrierBookingNumber: "",
    ContainerNumber: "",
    ContainerSizeType: "20SD86",
    ShipperLEI: "",
    ConsigneeLEI: "",
    NotifyPartyLEI: "",
    SealNumber: "WHLUO302017",
    SealSource: "",
    Address: "",
    PhoneNumber: "",
    Email: "",
    Fax: "",
    ContainerTareWeight: "",
    TransportDocumentNumber: "",
    ExportReferenceNumber: "",
    CountryOfOrigin: "",
    PreCarriedBy: "",
    OnBoardDate: "SEP",
    ReceivedForShipmentDate: "",
    SignedBy: "",
    Scac: "22AA",
    FreightAndCharges: "",
    PrepaidOrCollect: "",
    TermsAndConditions: "",
    TotalNumberOfContainers: "(0)",
    TotalNumberOfPackages: "BAGS",
    CarrierClauses: "",
    Unit: "",
    Currency: "",
    PrepaidAmount: "",
    CollectAmount: "",
    ServiceContract: "",
    DeclaredValue: "",
    Disclaimer:
      "LADING\nсору non-negõtiable\nFECEMED by the Cenhon the Sippen pood cden and condiion uries ohwse indicatd heten, the Goods, a te Containas a\npkapeaj said to contain the cargo haein metioned to te canied subjact toal he Ters and Conditions provided bra te lace and xkdf this Bill d\nLading by he imsnaned hemina ay sabstitte at the Carn's option and/arcŤa nas of taspt en te Pace el Receptar the Fort of lbading\nto the Fon al Dischage or the Place ol Delivay shown herein and there to be delivasd urto orden or assigns.\nhis Bl el lading duly endoned must be summdeed in echarge la the Coods adevey erdm\nIn accepting this Bll Lading, the Machant (as delined by Aricle 1 on the back heeo) ages to be bound ty all Tems and Canditions on the lace\nhe conary noheitstanding, and aps thai all apreements or he ght engagemenits lor and in comecionwih the Čamage ol the Goods aepeseded ty\nBll el Luding\nHis lurihan agred ta Goods may be stowed on deck wihat natice pursari to Articie 17 on he back of this Bil of Lading\nIt winess whenrol, the undesigned, on betall of the Canie, has signed therunitn ol Bilstol Lading staled altove, all ofkwar and date, ane of\nahich being accomplished the ahes to stand woid\n(Tis and Canditiors dB el Luding cortinud on thebk herel,y be dtuined lom the alfice al the Carien o he Cariers haised aprt,\nadae aailable an the website: inw ha com)\nshp baps, or ofta nes d anportation and ane in he stiody ol an inland or oan ci brCombined Tansport in axcondance with he tems ol\nREFERENCES (COMPLETE HAME AND ADDRESS)",
    TransportDocumentType: "W WAN HAI BILL OF",
    ReeferTemperatureSetting: "",
    ReeferHumidity: "",
    ReeferVentilation: "",
    PartLoadIndicator: "",
    ForwardingAgentReferenceNumber: "",
    ConsigneeReferenceNumber: "",
    PackageMeasurement: "213,516.000",
    PackageWeight: "KGS"
  }
};
