import { BillOfLading } from "./types";

export const BillOfLadingSample: BillOfLading = {
  $template: {
    type: "EMBEDDED_RENDERER",
    name: "BILL_OF_LADING",
    url: "http://localhost:3000"
  },
  links: {
    self: {
      href:
        "https://action.openattestation.com?q=%7B%22type%22%3A%22DOCUMENT%22%2C%22payload%22%3A%7B%22uri%22%3A%22https%3A%2F%2Fapi-rinkeby.tradetrust.io%2Fstorage%2F522f6929-2878-41d6-bd17-adc9170d897d%22%2C%22key%22%3A%22e834419b95a798f44323d2f590097b8566532eac22977219244048f0167d243b%22%2C%22permittedActions%22%3A%5B%22STORE%22%5D%2C%22redirect%22%3A%22https%3A%2F%2Frinkeby.tradetrust.io%2F%22%7D%7D"
    }
  },
  data: {
    BLNumber: "EGLV071100027449",
    CarrierName: "Evergreen Line",
    TransportDocumentIssuer: "",
    Shipper: "YAKULT MYANMAR CO.,LTD",
    ShipperAddress: "LOT A-18,ZONE A, THILAWA SPECIAL ECONOMIC ZONE,YANGON",
    ShipperCountry: "THE REPUBLIC OF THE UNION OF MYANMAR",
    ShipperPhoneNumber: "",
    ShipperEmail: "",
    ShipperFax: "",
    Consignee: "YAKULT PHILIPPINES, INC",
    ConsigneeAddress: "1461 AGONCILLO ST. CORNER, ESCODA STREETS ERMITA, METRO MANILA",
    ConsigneeCountry: "PHILIPPINES",
    ConsigneePhoneNumber: "",
    ConsigneeEmail: "",
    ConsigneeFax: "",
    FreightPayer: "",
    NotifyParty: "YAKULT PHILIPPINES, INC",
    NotifyPartyAddress: "1461 AGONCILLO ST. CORNER, ESCODA STREETS ERMITA, METRO MANILA",
    NotifyPartyCountry: "PHILIPPINES",
    NotifyPartyPhoneNumber: "",
    NotifyPartyEmail: "",
    NotifyPartyFax: "",
    AlsoNotify: "",
    ShipperForwardingAgent: "",
    ConsigneeForwardingAgent: "WIN & WIN UNIVERSE CO., LTD.(FORWARDING AND GENERAL SERVICES)",
    PlaceOfReceipt: "YANGON, MYANMAR",
    PortOfLoading: "YANGON, MYANMAR",
    PortOfDischarge: "MANILA (NORTHPORT),PHILIPPINES",
    PlaceOfDelivery: "MANILA (NORTHPORT),PHILIPPINES",
    OnwardInlandRouting: "",
    ServiceType: "FCL/FCL O/O",
    ShipmentTerms: "",
    Vessel: "EVER BLISS",
    VoyageNumber: "1830-054N",
    MarksAndNumbers: "NO MARKS",
    DescriptionOfGoods:
      "656 BAGS SKIM MILK POWDER EMAIL: KRISTOFFER.SANTOS@YAKULT.PHPHONE NUMBER: +63 2 8892 5858 EXT. 210** EMAIL:KRISTOFFER.SANTOS@YAKULT.PHPHONE NUMBER: +63 2 8892 5858 EXT. 210",
    Commodity: "",
    HsCode: "0402.10",
    CargoGrossWeight: "16,400.000 KGS",
    VerifiedGrossMass: "",
    Measurement: "25.0000 CBM",
    FreightPayableAt: "",
    PlaceOfIssue: "YANGON",
    DateOfIssue: "AUG.17,2021",
    NumberOfOriginalBL: "THREE (3)",
    NumberOfBLCopies: "",
    CarrierBookingNumber: "",
    ContainerNumber: "'",
    ContainerSizeType: "",
    ShipperLEI: "",
    ConsigneeLEI: "",
    NotifyPartyLEI: "",
    SealNumber: "EMCMTX9240",
    SealSource: "",
    Address: "",
    PhoneNumber: "",
    Email: "",
    Fax: "",
    ContainerTareWeight: "KGS",
    TransportDocumentNumber: "071100027449",
    ExportReferenceNumber: "",
    CountryOfOrigin: "",
    PreCarriedBy: "UNI-ACCORD 0240-691S",
    OnBoardDate: "AUG.17,2021",
    LadenOnBoard: "UNI-ACCORD 0240-691S YANGON",
    ReceivedForShipmentDate: "",
    SignedBy: "EVERGREEN INTERNATIONAL MYANMAR CO.,LTD",
    Scac: "EGLV",
    FreightAndCharges: "",
    PrepaidOrCollect: "PREPAID",
    TermsAndConditions: "",
    TotalNumberOfContainers: "ONE(1) CONTAINER ONLY",
    TotalNumberOfPackages: "1 X 20",
    CarrierClauses: "discharged",
    Unit: "",
    Currency: "",
    PrepaidAt: "SINGAPORE",
    PrepaidAmount: "",
    CollectAmount: "",
    ServiceContract: "",
    DeclaredValue: "",
    Disclaimer:
      "DUE TO THE UNSTABLE SITUATION IN MYANMAR, SHIPMENTS TO/FROM MYANMAR MAY FACE THE RISKS INCLUDING BUT NOT LIMITED TO CARGO DELAY, DETENTION, SUSPENSION, MIS-DELIVERY, MISSING AND/OR DAMAGE WHATSOEVER. ADDITIONAL COSTS INCLUDING BUT NOT LIMITED TO, COSTS OF PROLONGED STORAGE, DIVERSION, RESHIPMENT AND TRANSSHIPMENT, ETC. MAY ALSO BE INCURRED. MERCHANTS DULY ACKNOWLEDGE AND EXPRESSIVELY ACCEPT SUCH RISK AND SITUATION IS BEYOND THE CONTROL OF AND CONTROL OF AND AFFECTING THE ABILITY TO PERFORM THE SERVICE OF THE CARRIER. MERCHANTS FURTHER AGREE TO BE FULLY RESPONSIBLE FOR THE RISKS, LOSS, CLAIMS, COSTS AND EXPENSES CAUSED BY SUCH SITUATION IN MYANMAR AND WAIVE ALL THEIR CLAIM AGAINST CARRIER HEREINAFTER.",
    TransportDocumentType: "BILL OF LADING",
    ReeferTemperatureSetting: "",
    ReeferHumidity: "",
    ReeferVentilation: "",
    PartLoadIndicator: "",
    ForwardingAgentReferenceNumber: "",
    ForwardingAgentReferences: "",
    ConsigneeReferenceNumber: "",
    PackageMeasurement: "",
    PackageWeight: ""
  }
};
